### ISSUE TITLE
JavaScript example

### ISSUE THREAD

**Issue by padreputativo** [ava-cassiopeia/simple-switch#1]
Please i need a JavaScript example for the toggle, turn on or turn off events... I doesnt know how to properly use it. Using OnClick sounds a bit weird to me and i'm not sure if i'm using it properly...

This works clicking in the text but not in the toggle-button:

`<label><input type="checkbox" data-type="simple-switch" OnClick="alert(this.checked);" /> Text</label>`

This works clicking in the toggle-button and the text but clicking in the text doesnt change the toggle-button:

`<label OnClick="alert();" ><input type="checkbox" data-type="simple-switch"/> Text</label>`

Adding an ID to the input generates two alerts when clicking in the text but the toggle-button works:

`<label OnClick="alert(whatever.checked);"><input id="whatever" type="checkbox" data-type="simple-switch" /> text</label>`

It seems that the input is still visible and can be clicked. This is the html generated:

`<label><input id="whatever" type="checkbox" data-type="simple-switch" class="_simple-switch-checkbox"><button class="_simple-switch-track on" tabindex="-1" style="--simple-switch_size:16px;"><span class="handle"></span></button> text</label>`

I'm entirely lost

**Comment by aeolingamenfel** [comment]
The input will fire a `change` event ([Switch.js#L169](https://github.com/aeolingamenfel/simple-switch/blob/master/src/javascript/Switch.js#L169)) when the switch changes states, which you can subscribe to by attaching a `change` event listener to the element, for example:

```javascript
const switchEl = document.getElementById("mySwitchId");

switchEl.addEventListener("change", e => {
  // do something here
});
```

The change event should bubble up to a containing label, though I haven't personally tested this.

It may be worth, in the future, adding emitted events directly from `Switch` objects as well.
