### ISSUE TITLE
`input` event should be fired on click in addition to `change`

### ISSUE THREAD

**Issue by yjukaku** [ava-cassiopeia/simple-switch#15]
Hello there, thanks for your work on this library.

I ran into a bug recently where our app stopped detecting changes to the `input[type='checkbox']` enhanced by SimpleSwitch. It turns out that one of our dependencies stopped listening for `change` events and started listening for `input` events instead. Apparently, that's preferred over `change` because it's fired earlier for certain input types. Here's more info about the `input` event: https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/input_event

In any case, I think this library should fire both `input` and `change` events. I'm not sure if it's a breaking change (I would think not), but I'll leave that up to you. By default, both events are fired when you click on a checkbox input (See this fiddle: https://jsfiddle.net/rbyjx48h/ ). So adding the `input` event is actually bringing the library closer to the browser behavior, IMO.

**Comment by ava-cassiopeia** [comment]
Thank you for notifying me of this, it does seem like adding this event brings it closer to browser behavior, so I agree that this should be added.

As such, this feature should be in as-of version `0.7.0` (on NPM or here on GitHub). Please feel free to reopen if you have any issues or find any bugs!
